version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_batch
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql